config/routes.rb
Rails.application.routes.draw do
  #home
  root to: 'gossips#index'

  #pages menu
  get '/team', to: 'static_pages#team'
  get '/contact', to: 'static_pages#contact'

  #gossips
  resources :gossips do
    resources :comments, only: [:create, :edit, :update, :destroy]
  end

  #users
  resources:users, only: [:new, :create, :show]

  #cities
  resources:cities, only: [:show]

  #login/logout
  resources:sessions, only: [:new, :create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :gossip
  belongs_to :user
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :authenticate_user
    def index
      @comments = Comment.all
    end  
  
    def show
      @comment = Comment.find(params[:id])
    end  
  
    def new
      
    end  
  
    def create
        @gossip = Gossip.find(params[:gossip_id])
        @comment = Comment.create(content: params[:content], user_id: current_user.id, gossip_id: @gossip.id)
  
        if @comment.save
            redirect_to gossip_path(params[:gossip_id])
        else
            redirect_to gossip_path(params[:gossip_id]), alert: "Tu n'as rien écris ..."
        end
    end
  
    def edit
      @comment = Comment.find(params[:id])
    end
  
    def update
      @gossip = Gossip.find(params[:gossip_id]) 
      @comment = Comment.find(params[:id])
      if @comment.update(content: params[:content])
         redirect_to gossip_path(params[:gossip_id]) #changement pour bug edit 
        flash[:success] = "Le commentaire a bien été modifié!"
      else
        render :edit
        flash[:error] = "Le commentaire n'a pas un format valide, merci de le saisir à nouveau"
  
      end
    end
  
    def destroy
      @comment = Comment.find(params[:id])
        if @comment.destroy
        flash[:success] = "Ton commentaire a été correctement détruit!"
          redirect_to gossip_path(@comment.gossip.id)
        else
          render 'edit'
      end
    end  
  
    #private
  
    def comment_params
        params.require(:comment).permit(:content)
    end
  end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_index.html.erb
<div><% @comments.sort_by(&:created_at).each do |comment| %>
  <div class="card bg-light text-right my-2">
    <div class="card-header ">
      <p ><%= comment.content %></p>
      <footer class="blockquote-footer">
        <strong><%= link_to "#{comment.user.first_name + " " + comment.user.last_name}", user_path(comment.user.id) %></strong>
          <cite title="Source Title">
            <% if current_user.id == comment.user_id%>
              <%= link_to "Editer", edit_gossip_comment_path(@gossip.id, comment.id), class:"badge badge-success" %>
              <%= link_to "Supprimer", gossip_comment_path(@gossip.id, comment.id), class:"badge badge-danger", data:{confirm:"Etes vous sûr de vouloir supprimer ce potin ?", method:"DELETE"} %>
            <% end %>
          </cite>
      </footer>
    </div>
  </div>
<% end %></div>

app/views/comments/_new.html.erb
<div class="container mt-5 form-group">
 <%= form_tag gossip_comments_path(@gossip), method: "post" do %>
      <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
      <div class="d-flex flex-row justify-content-center">

      <%= text_field_tag 'content', @comment.content, class:"form-control mx-2", placeholder:"What have you got to say" %>

      <%= submit_tag "Comment!", class:"btn btn-primary"%>
      </div>
    <% end %>
</div>

app/views/comments/edit.html.erb
<% if @comment.errors.any? %>
    <% @comment.errors.full_messages.each do |message| %>
      <p class="alert alert-danger d-flex justify-content-center" role="alert"><%= message %></p>
    <% end %>
<% end %>

<div class="container mt-5 form-group">
 <%= form_tag url_for(action: 'update'), method: "patch" do %>
      <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

      <strong><%= label_tag 'Contenu du commentaire' %></strong>
      <%= text_area_tag 'content', @comment.content, class:"form-control" %>
      <br />

      <div class="d-flex justify-content-center"><%= submit_tag "Editer le commentaire", class:"btn btn-success btn-lg"%></div>

    <% end %>
        <hr>
    <div style="margin-top: 10px;" class="d-flex justify-content-center"><%= link_to "Retour Accueil", root_path, :class => "btn btn-info btn-sm" %></div>
</div>