config/routes.rb
Rails.application.routes.draw do
  #home
  root to: 'gossips#index'

  #pages menu
  get '/team', to: 'static_pages#team'
  get '/contact', to: 'static_pages#contact'

  #gossips
  resources :gossips do
    resources :comments, only: [:create, :edit, :update, :destroy]
  end

  #users
  resources:users, only: [:new, :create, :show]

  #cities
  resources:cities, only: [:show]

  #login/logout
  resources:sessions, only: [:new, :create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  belongs_to :user
  has_many :gossip_tags
  has_many :tags, through: :gossip_tags
  has_many :comments
  validates :title,
    presence: true,
    length: { minimum: 3, maximum: 14 }


  validates :content,
    presence: true
end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController
  before_action :authenticate_user, except: [:index]
  # View a list of gossips
  def index
    @gossips = Gossip.all

    # Méthode qui récupère tous les potins et les envoie à la view index (index.html.erb) pour affichage
  end

  def show
    @gossip = Gossip.find(params[:id])
    @comment = Comment.new
    @comments = @gossip.comments
    # Méthode qui récupère le potin concerné et l'envoie à la view show (show.html.erb) pour affichage
  end

  def new
    @gossip = Gossip.new(title: "", content: "", user: User.last)
    # Méthode qui crée un potin vide et l'envoie à une view qui affiche le formulaire pour 'le remplir' (new.html.erb)
  end

def create
    @gossip = Gossip.new(user: current_user, title: params[:title], content: params[:content])

    if @gossip.save      
      redirect_to "/"
      flash[:success] = "Le gossip a bien été créé!"
    else
      flash[:error] = "Le gossip n'a pas un format valide, merci de le saisir à nouveau"
      render :new
      
    end
  end

  def edit
    @gossip = Gossip.find(params[:id])
    # Méthode qui récupère le potin concerné et l'envoie à la view edit (edit.html.erb) pour affichage dans un formulaire d'édition
  end

  def update
    @gossip = Gossip.find(params[:id])
    if @gossip.update(user: User.first, title: params[:title], content: params[:content])
      redirect_to "/"
      flash[:success] = "Le gossip a bien été modifié!"
    else
      flash[:error] = "Le gossip n'a pas un format valide, merci de le saisir à nouveau"
      render :edit
    end
  end

  def destroy
    @gossip = Gossip.find(params[:id])
    if current_user?(@gossip.user)
      @gossip.delete
      flash[:danger] = 'Tu as supprimé un potin !'
    else
      flash[:danger] = "You can't modify or delete a gossip you didn't create"
      render 'index'
    end      
  end
end

app/helpers/gossip_helper.rb
module GossipHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/views/gossips/create.html.erb
<h1>Gossips#create</h1>
<p>Find me in app/views/gossips/create.html.erb</p>

app/views/gossips/edit.html.erb
<html>
  <head>
    <title>The Gossip Project</title>
  </head>
  <body>
    <div class="container text-center mt-5">
      <h1 style="color: #053557">Modifier un Gossip !</h1>
      <div class="m-5">
        <%= form_tag url_for(action: 'update'), method: "put" do %>

          <%= label_tag 'Titre' %> <br/>
          <%= text_field_tag 'title' %>
          <br /> <br />

          <%= label_tag 'Contenu' %> <br/>
          <%= text_area_tag 'content' %>
          <br /> <br />

          <%= submit_tag "Modifier" %> 
        <% end %>
        
    </div>
  </body>
</html>

app/views/gossips/index.html.erb
<!doctype html>
<html lang="en">

  <body>
  <% if !flash[:success].nil? %>
    <div class="alert alert-success" role="alert"><%= flash[:success] %></div>
  <% end %>
  <% if !flash[:update].nil? %>
    <div class="alert alert-success" role="alert"><%= flash[:update] %></div>
  <% end %>
  <div>
  <%if session[:user_id] != nil%>
    <h1>Hey <%= current_user.first_name %></h1>
  <%else %>
    <%if params[:first_name] == nil%>
      <h1>Welcome hot stranger</h1>
    <%elsif params[:action] == "create" && params[:commit] == "S'inscrire"%>
      <h1>Welcome on our gossip website, <%= params[:first_name] %></h1>
    <%else %>
      <h1>Welcome <%= params[:first_name] %></h1>
  <% end %>
  <% end %>
  </div>
  
  <main class="container">
  <br>    
    <div class="jumbotron jumbotron-hero px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
      <div class="container">
        <br>
        <br>
        <br>
        <br>
        <h2><%= link_to "Create a new gossip", new_gossip_path, class:"btn btn-outline-info mx-1 my-1" %></h2>
      </div>
    </div>

  <h2>Here's some juicy gossip for you : </h2>
  <div class="row row-cols-5 row-cols-md-3  p-md-0 m-md-0 d-flex justify-content-center">
    <% Gossip.all.sort.each do |gossip| %>
      <div class="card border-info text-center bg-light my-3 mx-3" style="max-width: 18rem;"> 
        <div class="card-body">
          <h5 class="card-title"><%= gossip.user.first_name %></h5>
          <p class="card-text"><%= gossip.title %></p>
        </div>
        <div class="card-footer">
          <%= link_to "See more", gossip_path(gossip.id), class:"btn btn-outline-info mx-1 my-1" %>
          <% if current_user%>
            <% if current_user.id == gossip.user_id%>
              <%= link_to "", user_path(current_user.id), class:"fas fa-star mx-1 my-1", style:"color:#efd807;" %>
            <% end %>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</main>
  </body>

</html> 

app/views/gossips/new.html.erb
<html>
  <head>
    <title>The Gossip Project</title>
  </head>
  <body>

    <% if @gossip.errors.any? %>
      <div class="alert alert-danger" role="alert"><%= flash[:error] %></div>
    <% end %>

    <div class="container text-center mt-5">
      <h1 style="color: #053557">Créer ton propre Gossip !</h1>
      <div class="m-5">
        <%= form_tag url_for(action: 'create'), method: "post" do %>

          <%= label_tag 'Titre' %> <br/>
          <%= text_field_tag 'title' %>
          <br /> <br />

          <%= label_tag 'Contenu' %> <br/>
          <%= text_area_tag 'content' %>
          <br /> <br />

          <%= submit_tag "Créer" %> 
        <% end %>
        
    </div>
  </body>
</html>

app/views/gossips/show.html.erb
<!doctype html>
<html lang="en">

  <body>

    <div class="container">
      <h1 class="display-4 text-center my-3">The Gossip Project</h1>

      <div class="row justify-content-center">
          <div class="col-6">
            <div class="card">
              <img class="card-img-top" alt="Card image cap" src="https://hiro.pl/wp-content/uploads/2017/05/twin.jpg">
              <div class="card-body">
                <h5 class="card-title"><%=@gossip.title %></h5>
                <p class="card-text"><%= @gossip.content %></p>
                <p class="card-text">
                <p class="card-text">
                <p class="card-text"><a href="<%= city_path(@gossip.user.city.id) %>"><%= @gossip.user.city.name %></p></a>
                  <small class="text-muted">
                    posté par <a href="<%= user_path(@gossip.user.id) %>"><%=@gossip.user.first_name %></a>
                    le <%=@gossip.created_at.strftime("%d/%m/%Y à %H:%I") %> à <%=@gossip.user.city.name %>
                  </small>
                </p>
                <div class="row justify-content-center">
                  <div class="col">
                    <a class='btn btn-info btn-block' href="<%= edit_gossip_path %>">Editer</a>
                  </div>
                  <div class="col">
                    <%= form_tag gossip_path(@gossip.id), method: "delete" do %>
                    <%= submit_tag "Supprimer", {class: 'btn btn-danger btn-block'} %>
                    <% end %>
                  </div>
                </div>
              </div>
              </div>
            </div>
          </div>
      </div>
          
<div justify-content-center>

      <h2>Commentaires :</h2>
          <div>
            <%= render 'comments/index'%>
            <%= render 'comments/new'%>
          </div>
      </div>
  </body>

</html>

app/views/gossips/update.html.erb
<h1>Gossips#update</h1>
<p>Find me in app/views/gossips/update.html.erb</p>